// ignore_for_file: constant_identifier_names

enum SharedPreferenceKey {
  DASHBOARD_UI_TYPE("DASHBOARD_UI_TYPE"),
  GLASS_BACKGROUND_PATH("GLASS_BACKGROUND_PATH"),
  GLASS_BACKGROUND_REMOTE_URL("GLASS_BACKGROUND_REMOTE_URL"),
  GLASS_BACKGROUND_REMOTE_PATH("GLASS_BACKGROUND_REMOTE_PATH"),
  GLASS_BACKGROUND_ALLOW_GALLERY("GLASS_BACKGROUND_ALLOW_GALLERY"),
  GLASS_BACKGROUND_SOURCE("GLASS_BACKGROUND_SOURCE"),
  GLASS_BACKGROUND_REMOTE_URLS("GLASS_BACKGROUND_REMOTE_URLS"),
  GLASS_BACKGROUND_REMOTE_PATHS("GLASS_BACKGROUND_REMOTE_PATHS"),
  GLASS_BACKGROUND_PORTRAIT_URLS("GLASS_BACKGROUND_PORTRAIT_URLS"),
  GLASS_BACKGROUND_PORTRAIT_PATHS("GLASS_BACKGROUND_PORTRAIT_PATHS"),
  GLASS_BACKGROUND_LANDSCAPE_URLS("GLASS_BACKGROUND_LANDSCAPE_URLS"),
  GLASS_BACKGROUND_LANDSCAPE_PATHS("GLASS_BACKGROUND_LANDSCAPE_PATHS"),
  WALLPAPER_CHANGED_FLAG("WALLPAPER_CHANGED_FLAG"),
  WALLPAPER_PORTRAIT_BASE64("WALLPAPER_PORTRAIT_BASE64"),
  WALLPAPER_LANDSCAPE_BASE64("WALLPAPER_LANDSCAPE_BASE64"),
  WALLPAPER_USER_BASE64("WALLPAPER_USER_BASE64"),
  WEB_WALLPAPER_BYTES("WEB_WALLPAPER_BYTES"),
  WEB_DEVICE_ID("WEB_DEVICE_ID");

  final String? legacyKey;

  const SharedPreferenceKey(this.legacyKey);
}
