name: dynamic_of_things
description: Dynamic of things
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  base:
    git:
      url: https://github.com/sisappmobile/base.git
      ref: 2.0.3

  # inherited from base
  get: 4.7.2
  dio: 5.8.0+1
  basic_utils: 5.8.2
  jiffy: 6.4.3
  shared_preferences: 2.5.3
  syncfusion_flutter_datepicker: 29.2.7
  lottie: 3.3.1
  easy_localization: 3.0.7+1
  photo_view: 0.15.0
  video_player: 2.9.5
  pattern_formatter: 4.0.0
  file_picker: 10.1.9
  image_picker: 1.1.2
  smooth_corner: 1.1.1
  collection: 1.19.1
  dotted_border: 3.0.1
  camera: 0.11.1
  flutter_image_compress: 2.4.0
  timer_count_down: 2.2.2
  detect_fake_location: 2.2.0+1
  geolocator: 14.0.1
  go_router: 15.1.2

  # plugins
  path_provider: 2.1.5
  googleapis: 13.1.0
  googleapis_auth: 1.5.0
  video_thumbnail: 0.5.3
  mobile_scanner: 3.5.5
  material_symbols_icons: 4.2815.1
  validators: 3.0.0
  image_watermark: 0.1.0
  geocoding: 3.0.0
  loader_overlay: 5.0.0
  flutter_bloc: 9.1.1
  shimmer: 3.0.0
  syncfusion_flutter_charts: 29.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: 0.20.2