// ignore_for_file: avoid_single_cascade_in_expression_statements

import "package:base/base.dart";
import "package:basic_utils/basic_utils.dart";
import "package:flutter/foundation.dart";
import "package:sqflite/sqflite.dart";

class Sqlites {
  static Database? database;

  static Future<Database> get() async {
    if (database == null) {
      if (kDebugMode) {
        // Use the debugQuickLoggerWrapper on the default factory
        databaseFactory.debugQuickLoggerWrapper();
        // Temporarily turn on SQL logging on the console
        await databaseFactory.debugSetLogLevel(sqfliteLogLevelVerbose);
      }

      database = await openDatabase(
        "${await getDatabasesPath()}/dynamic_of_things.db",
        version: 1,
        singleInstance: false,
        onCreate: (db, version) async {
          const tableScripts = [
            "CREATE TABLE _sequences ( id TEXT PRIMARY KEY, value INTEGER )",
            "CREATE TABLE _sync_queues ( id TEXT PRIMARY KEY, entity TEXT, payload TEXT, created_at TEXT )",
            "CREATE TABLE c_custom_form( id INTEGER NOT NULL PRIMARY KEY, category_id INTEGER, company_id INTEGER, form_code TEXT, form_desc TEXT, form_requirements text, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_journey TEXT, f_form_existing TEXT, f_show_last_data TEXT, version INTEGER, f_visit TEXT, f_active TEXT, f_requirements TEXT, \"index\" INTEGER, f_all_bu TEXT, f_detail TEXT, table_header_id INTEGER, table_detail_id INTEGER, template_mode TEXT, f_menu_system TEXT, function_id TEXT, f_send_notification TEXT, source_table_notif_id INTEGER, f_send_notification_create TEXT default 'N', f_send_notification_update TEXT default 'N', f_send_notification_in_active TEXT default 'N', f_header TEXT, header_table_id INTEGER, f_notif_not_by_template TEXT, f_notif_by_template TEXT, f_multiple_detail TEXT, table_multiple_id INTEGER, caption_detail TEXT, f_use_multiple TEXT, reminder_web TEXT, source_table_load_id INTEGER, f_choose_icon TEXT, table_schedule_id INTEGER, f_allow_schedule TEXT, module_origin_id INTEGER, f_script_formula TEXT, script_formula text, f_record_location_on_submit TEXT, base_path_icon text, f_waktuqu TEXT, f_sub_detail TEXT, f_creator TEXT, f_user_group TEXT, list_user_group text, send_to TEXT, field_structure TEXT, details_message text, subject_notification TEXT, f_structure TEXT, f_by_field_value TEXT, by_field_value_id INTEGER, f_multpile_condition TEXT, f_sub_detail_multiple TEXT, global_variable text, f_store_history TEXT, history_show_column text, f_mandatory TEXT, f_add_more_notification TEXT, load_table_detail_id INTEGER, f_sort_list TEXT, f_validasi_periode TEXT, f_show_in_sidebar TEXT, f_to_module_system TEXT, color_bg_menu TEXT, color_bg_font TEXT, src_table_default_header INTEGER, f_is_online TEXT, f_can_offline TEXT, f_viewers TEXT, table_name_viewers TEXT, sequence_name_viewers TEXT, f_show_in_dashboard TEXT, location_accuracy_in_meters REAL, location_accuracy_effective_duration_in_seconds REAL, f_create_using_scan_qr TEXT, source_table_qr_id INTEGER, source_field_qr_id INTEGER, using_qr_type TEXT, f_create_from_reference TEXT, source_table_reference_id INTEGER, source_field_key_reference_id INTEGER, width_detail_column INTEGER, detail_index INTEGER )",
            'CREATE TABLE c_custom_form_category ( id INTEGER NOT NULL PRIMARY KEY, description TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, "index" INTEGER, module_id INTEGER, module_origin_id INTEGER, f_choose_icon TEXT, base_path_icon text, version INTEGER )',
            "CREATE TABLE c_custom_functions ( function_id TEXT NOT NULL CONSTRAINT pk_c_custom_functions PRIMARY KEY, custom_id INTEGER NOT NULL, function_name TEXT, resource_id TEXT, f_default TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, btn_delete TEXT, f_show_inlist TEXT, f_function_system TEXT, script_before text, script_after text, custom_type TEXT, script_before_mobile text, script_after_mobile text, script_afte_mobiler text, pseudo_code TEXT )",
            "CREATE TABLE c_custom_functions_action ( id TEXT NOT NULL CONSTRAINT pk_c_custom_functions_action PRIMARY KEY, function_id TEXT NOT NULL, key TEXT, value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_custom_functions_validation ( id TEXT NOT NULL CONSTRAINT pk_c_custom_functions_validation PRIMARY KEY, function_id TEXT NOT NULL, key TEXT, operator TEXT, value TEXT, operation TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_custom_report_detail ( id INTEGER NOT NULL CONSTRAINT c_custom_report_detail_pk PRIMARY KEY, custom_report_id INTEGER NOT NULL, form_id INTEGER NOT NULL, field_id INTEGER NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, form_index INTEGER NOT NULL, field_index INTEGER NOT NULL, relation_to_modul_id INTEGER, join_type TEXT, relation_key_to_field_id INTEGER, field_filterable TEXT, f_show_form TEXT, f_show_field TEXT )",
            "CREATE TABLE c_dd_list_filter ( id INTEGER NOT NULL PRIMARY KEY, dropdown_id INTEGER, key TEXT, operator TEXT, value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, operation TEXT, f_default TEXT )",
            "CREATE TABLE c_depend_on_form ( id INTEGER NOT NULL CONSTRAINT c_depend_on_form_pk PRIMARY KEY, custom_id INTEGER NOT NULL, depend_on_form_id INTEGER NOT NULL, relation_field_id TEXT NOT NULL, depend_on_field_key INTEGER NOT NULL, depend_on_field_id INTEGER, depend_on_field_value TEXT, operator TEXT, operation TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_drop_down_list ( id INTEGER NOT NULL PRIMARY KEY, dropdown_name TEXT, form_id INTEGER, field_select INTEGER, field_show INTEGER, f_allow_add_new TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER )",
            "CREATE TABLE c_field_custom_form ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, field_name TEXT, field_caption TEXT, field_data_type TEXT, field_data_length INTEGER, field_precision INTEGER, f_pk TEXT, f_uk TEXT, f_mandatory TEXT, index_field INTEGER, f_default TEXT, group_field_name TEXT, group_field_index INTEGER, field_data_value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_subject TEXT, f_description TEXT, f_show_list TEXT, f_dropdown_list TEXT, dropdown_list_id INTEGER, f_filter_data_record TEXT, f_readonly TEXT, f_textarea TEXT, column_id INTEGER, column_data_select text, f_default_value TEXT, default_value TEXT, f_unique_value TEXT, f_all_file TEXT, file_type TEXT, file_size INTEGER, f_load_detail TEXT, src_form_detail_id INTEGER, f_filter_selector TEXT, f_link_value TEXT, src_link_field_value TEXT, dst_link_field_value TEXT, f_allow_create_link TEXT, script text, f_send_notification_update TEXT default 'N', f_send_notification_create TEXT default 'N', f_send_notification_in_active TEXT default 'N', f_send_notification TEXT default 'N', f_hidden TEXT, src_form_header_id INTEGER, src_table_header INTEGER, is_src_table_header TEXT, f_from_now TEXT default 'N', enable_after_colum INTEGER, change_action TEXT, script_android text, f_manual_relation TEXT, src_field_header_id TEXT, f_link_table TEXT, src_table_for_qrcode_id INTEGER, src_field_for_condition_qrcode_id INTEGER, src_form_detail_qrcode_id INTEGER, f_sub_detail_load_detail TEXT, src_field_detail_id INTEGER, src_form_sub_detail_id INTEGER, f_ckeditor TEXT, f_refresh_detail_value TEXT, f_special_character TEXT, special_character TEXT, f_hashing TEXT, f_manual_relation_sub TEXT, field_key_sub TEXT, val_field_key_sub TEXT, link_table_sub TEXT, dst_detail_form_id INTEGER, f_auto_load_detail_form TEXT, f_load_on_field_default TEXT, f_load_on_field_default_header TEXT, f_load_on_field_default_detail TEXT, src_table_default_header TEXT, src_field_default_header TEXT, src_table_default_detail TEXT, src_field_default_detail TEXT, src_field_default_detail_relation_on_header TEXT, f_use_segment_query_header TEXT, f_use_segment_query_detail TEXT, f_is_link_url TEXT, f_default_value_as_now TEXT, order_view text, f_allow_create TEXT, pseudo_code TEXT )",
            "CREATE TABLE c_field_filter_from_field ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, key TEXT, operator TEXT, value TEXT, operation TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_load_header TEXT, f_link_value TEXT )",
            "CREATE TABLE c_field_load_on_field ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_load_detail TEXT, f_link_value TEXT )",
            "CREATE TABLE c_field_load_on_field_detail ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_filter_field_list_data ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, key TEXT, operator TEXT, value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, operation TEXT, f_default TEXT, f_from_login TEXT, f_from_now TEXT )",
            "CREATE TABLE c_group_access_custom_form ( id INTEGER NOT NULL PRIMARY KEY, description TEXT NOT NULL, code TEXT NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER )",
            "CREATE TABLE c_group_access_custom_form_detail ( id INTEGER NOT NULL PRIMARY KEY, group_id INTEGER NOT NULL, user_id TEXT NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_mapping_custom_form ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, bu_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_trigger_custom_form ( id INTEGER NOT NULL CONSTRAINT c_trigger_custom_form_pk PRIMARY KEY, src_modul_id INTEGER, src_field_key_code TEXT, src_field_id TEXT, src_operator_value TEXT, src_value TEXT, dst_field_key_code TEXT, dst_modul_id INTEGER, dst_field_id TEXT, dst_value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_user_access_custom_form ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, group_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, custom_type TEXT )",
            "CREATE TABLE c_user_access_function_custom_form ( id INTEGER NOT NULL PRIMARY KEY, access_id INTEGER, resource_id TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_segment_report ( id INTEGER NOT NULL PRIMARY KEY, company_id INTEGER, segment_report_name TEXT, segment_report_query TEXT, view_name TEXT, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT, module_origin_id INTEGER )",
            'CREATE TABLE c_custom_report ( id INTEGER NOT NULL CONSTRAINT c_custom_report_pk PRIMARY KEY, category_id INTEGER NOT NULL, report_name TEXT NOT NULL, bu_id INTEGER NOT NULL, company_id INTEGER NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, segment_id INTEGER NOT NULL CONSTRAINT c_custom_report_fk references c_segment_report on delete restrict, f_active TEXT, "index" INTEGER, module_origin_id INTEGER, f_pivot_mode TEXT, f_show_map TEXT, f_chart TEXT, type_chart TEXT, print_out_by_group TEXT, f_template_daily_activity_detail TEXT, f_template_activity_summary_monthly TEXT, f_template_activity_use_summary_monthly TEXT, f_template_activity_report TEXT, f_template_imaging TEXT, field_name_for_sales TEXT, field_name_for_target_perbulan TEXT, field_name_for_tanggal_transaksi TEXT, field_name_for_nominal_transaksi TEXT, color_bg_menu TEXT, color_bg_font TEXT, field_grouping_for_imaging_report TEXT, f_link_to TEXT, order_view text )',
            "CREATE TABLE c_custom_report_field ( id INTEGER NOT NULL CONSTRAINT c_custom_report_field_pk PRIMARY KEY, custom_report_id INTEGER NOT NULL, field_name TEXT, field_caption TEXT, field_type TEXT, formatting TEXT, field_index INTEGER NOT NULL, f_show_field TEXT, company_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_show_summary TEXT, f_photo TEXT, latitude TEXT, longitude TEXT, f_title_show_map TEXT, f_subject_chart TEXT, f_show_in_chart TEXT, color_chart TEXT, f_activity_title TEXT, f_activity_subtitle TEXT, f_activity_date TEXT, f_activity_monthly_cabang TEXT, f_activity_monthly_name TEXT, f_activity_monthly_summary TEXT, f_activity_monthly_tanggal TEXT, f_field_filtering TEXT )",
            "CREATE TABLE c_custom_report_filter ( id INTEGER NOT NULL CONSTRAINT c_custom_report_filter_pk PRIMARY KEY, custom_report_id INTEGER NOT NULL, field_name TEXT, field_caption TEXT, field_type TEXT, field_operator TEXT, default_value TEXT, field_index INTEGER NOT NULL, company_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, lov_type TEXT, f_manual_hidden TEXT, f_multiple TEXT, logic_operator TEXT )",
            "CREATE TABLE c_field_formatting ( id INTEGER NOT NULL PRIMARY KEY, code TEXT, type TEXT, description TEXT )",
            "CREATE TABLE c_custom_form_deleted ( custom_form_id INTEGER, version REAL, deleted_time TEXT )",
            "CREATE TABLE c_custom_functions_query_action ( id TEXT NOT NULL CONSTRAINT pk_c_custom_functions_query_validation PRIMARY KEY, function_id TEXT NOT NULL, query_action_id INTEGER, index_action INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_custom_query_action ( id INTEGER NOT NULL CONSTRAINT c_custom_action_pkey PRIMARY KEY, action_name TEXT, custom_id INTEGER, segment_id INTEGER, output TEXT, create_who TEXT, create_date TEXT, change_who TEXT, change_date TEXT, message TEXT, condition TEXT )",
            "CREATE TABLE c_custom_query_action_field ( id INTEGER NOT NULL CONSTRAINT c_custom_query_action_field_pk PRIMARY KEY, custom_query_action_id INTEGER NOT NULL, field_name TEXT, field_caption TEXT, field_type TEXT, formatting TEXT, field_index INTEGER NOT NULL, f_show_field TEXT, company_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_custom_query_action_filter ( id INTEGER NOT NULL CONSTRAINT c_custom_action_filter_pkey PRIMARY KEY, custom_query_action_id INTEGER, field_name TEXT, field_type TEXT, field_operator TEXT, f_manual TEXT, manual_value TEXT, dst_custom_field_name TEXT, field_operation TEXT, create_who TEXT, create_date TEXT, change_who TEXT, change_date TEXT, f_multiple TEXT )",
            "CREATE TABLE c_field_filter_from_field_header ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, key TEXT, operator TEXT, value TEXT, operation TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_load_header TEXT, f_link_value TEXT, field_header_key INTEGER )",
            "CREATE TABLE c_custom_filter_field ( id INTEGER NOT NULL CONSTRAINT c_custom_filter_field_pk PRIMARY KEY, table_id INTEGER, f_manual_hidden TEXT, field_caption TEXT, field_type TEXT, field_operator TEXT, lov_type TEXT, default_value TEXT, company_id INTEGER, custom_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, field_index INTEGER, field_name TEXT, manual_column TEXT )",
            'CREATE TABLE c_custom_form_multiple_detail ( id INTEGER NOT NULL PRIMARY KEY, category_id INTEGER, company_id INTEGER, table_header_id INTEGER, table_detail_id INTEGER, custom_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, "index" INTEGER )',
            "CREATE TABLE c_group_access_sales_unit_custom_form ( id INTEGER NOT NULL PRIMARY KEY, description TEXT NOT NULL, code TEXT NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER )",
            "CREATE TABLE c_group_access_sales_unit_custom_form_detail ( id INTEGER NOT NULL PRIMARY KEY, group_id INTEGER NOT NULL, user_id TEXT NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, custom_id INTEGER, company_id INTEGER )",
            "CREATE TABLE c_load_field_custom_form ( id INTEGER NOT NULL PRIMARY KEY, table_id INTEGER, table_multi_detail_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, bussnies_unit INTEGER, custom_id INTEGER, version INTEGER, table_multi_detail_name TEXT )",
            "CREATE TABLE c_load_field_detail_custom_form ( id INTEGER NOT NULL PRIMARY KEY, load_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, bussnies_unit INTEGER, custom_id INTEGER, version INTEGER, multiple_detail_id INTEGER )",
            "CREATE TABLE c_sales_access_function_custom_form ( id INTEGER NOT NULL PRIMARY KEY, access_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, resource_id TEXT )",
            "CREATE TABLE c_sales_access_custom_form ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, group_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, custom_type TEXT )",
            "CREATE TABLE c_menu_default_sfa ( id INTEGER NOT NULL PRIMARY KEY, nama_menu TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_menu_default_header_sfa ( id INTEGER NOT NULL PRIMARY KEY, salesunit_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, sales_name TEXT )",
            "CREATE TABLE c_menu_default_detail_sfa ( id INTEGER NOT NULL PRIMARY KEY, header_id INTEGER, name_menu_category TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, index_field INTEGER )",
            "CREATE TABLE c_menu_name_default_detail_sfa ( id INTEGER NOT NULL PRIMARY KEY, menu_header_id INTEGER, menu_category_id INTEGER, company_id INTEGER, salesunit_id INTEGER, index_field INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, menu_sfa_id INTEGER )",
            "CREATE TABLE c_menu_icon_detail ( id INTEGER NOT NULL PRIMARY KEY, header_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, bussnies_unit INTEGER, f_delete TEXT, menu_sfa_id INTEGER, f_upload TEXT )",
            "CREATE TABLE c_menu_icon ( id INTEGER NOT NULL PRIMARY KEY, sales_unit_id INTEGER, sales_name TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, bussnies_unit INTEGER, f_delete TEXT )",
            "CREATE TABLE c_default_icon_path ( id INTEGER NOT NULL PRIMARY KEY, path_text text )",
            'CREATE TABLE c_custom_form_module ( module_id INTEGER NOT NULL PRIMARY KEY, description TEXT, company_id INTEGER, "index" INTEGER, f_public TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, module_origin_id INTEGER, icon INTEGER, module_name TEXT, documentation_link TEXT, documentation_file TEXT, version INTEGER )',
            "CREATE TABLE c_field_load_on_field_qrcode ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_field_load_on_field_qrcode_detail ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_custom_form_sub_detail ( id INTEGER NOT NULL CONSTRAINT c_custom_form_sub_detail_pk PRIMARY KEY, custom_id INTEGER, custom_detail_id INTEGER, custom_detail_header_id INTEGER, detail_layer TEXT, f_delete TEXT, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT, f_multiple TEXT )",
            "CREATE TABLE c_user_group_header ( id INTEGER NOT NULL PRIMARY KEY, code_group TEXT, nama_group TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, bussnies_unit INTEGER, version INTEGER, f_delete TEXT )",
            "CREATE TABLE c_user_group_detail ( id INTEGER NOT NULL PRIMARY KEY, user_group_id INTEGER NOT NULL, user_source TEXT, user_id TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, bussnies_unit INTEGER, version INTEGER, f_delete TEXT, CONSTRAINT c_user_group_detail_unique unique (user_group_id, user_source, user_id) )",
            "CREATE TABLE c_reciver_notification ( id INTEGER NOT NULL PRIMARY KEY, type TEXT, value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, custom_id INTEGER, version INTEGER, f_delete TEXT, group_condition_id INTEGER, multiple_notification_id INTEGER )",
            "CREATE TABLE c_relation_custom_form ( id INTEGER NOT NULL PRIMARY KEY, company_id INTEGER, custom_form_id INTEGER, field_src_name TEXT, field_name TEXT, custom_form_src_id INTEGER, create_who TEXT, create_date TEXT, change_who TEXT, change_date TEXT, f_delete TEXT )",
            'CREATE TABLE c_custom_multiple_detail ( id INTEGER NOT NULL PRIMARY KEY, company_id INTEGER, bu_id INTEGER, custom_id INTEGER, caption_detail TEXT, table_id INTEGER, table_load_on_field INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, version REAL, f_mandatory TEXT, table_reference_id INTEGER, "index" TEXT )',
            "CREATE TABLE c_custom_report_grouping ( id INTEGER NOT NULL PRIMARY KEY, field_name TEXT, custom_report_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version REAL, f_delete TEXT, f_summary_group TEXT )",
            "CREATE TABLE c_custom_report_grouping_summary_group ( id INTEGER NOT NULL PRIMARY KEY, field_name TEXT, custom_report_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version REAL, f_delete TEXT )",
            "CREATE TABLE c_custom_report_grouping_summary_column ( id INTEGER NOT NULL PRIMARY KEY, field_name TEXT, bu_id INTEGER, custom_report_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, doc_external_number TEXT, f_delete TEXT, version REAL )",
            "CREATE TABLE c_field_load_on_field_sub_detail ( id INTEGER NOT NULL PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_multiple_notification ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, f_create TEXT, f_update TEXT, caption TEXT, subject TEXT, description text, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, type_notif_id INTEGER, type_notif_name TEXT, f_active TEXT, f_reminder TEXT, field_target_value_id INTEGER, count_reminder REAL, type_time_remider TEXT )",
            "CREATE TABLE c_custom_form_group ( id INTEGER NOT NULL PRIMARY KEY, form_id INTEGER, form_group_id INTEGER, form_group_index TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, based_form_origin_id INTEGER )",
            "CREATE TABLE c_custom_form_validasi_date ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, field_name_first TEXT, condition TEXT, field_name_second TEXT, f_delete TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT )",
            "CREATE TABLE c_custom_grouping_template_report ( id INTEGER NOT NULL PRIMARY KEY, field_name TEXT, custom_report_id INTEGER, field_caption TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version REAL, f_delete TEXT )",
            "CREATE TABLE c_print_out_by_your_template ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, caption TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, file_template INTEGER, f_active TEXT )",
            "CREATE TABLE c_print_out_by_your_template_configuration ( id INTEGER NOT NULL PRIMARY KEY, custom_id INTEGER, current_field INTEGER, inisial TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, print_out_by_your_template_id INTEGER )",
            "CREATE TABLE c_print_out_by_your_template_kriteria ( id INTEGER NOT NULL PRIMARY KEY, print_out_by_your_template_id INTEGER, field_key INTEGER, operator TEXT, value TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT )",
            "CREATE TABLE c_custom_form_variable ( id INTEGER NOT NULL PRIMARY KEY, custom_form_id INTEGER NOT NULL, variable_name TEXT, f_query TEXT, f_session TEXT, query_form_id INTEGER, session_name TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, f_current TEXT, f_manual TEXT, operation text, order_by text, order_sort TEXT, list_limit TEXT )",
            "CREATE TABLE c_field_load_on_field_default_header ( id INTEGER NOT NULL CONSTRAINT c_field_load_on_field_default_header_pk PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_field_load_on_field_default_detail ( id INTEGER NOT NULL CONSTRAINT c_field_load_on_field_default_detail_pk PRIMARY KEY, field_id INTEGER, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_field_load_on_field_default ( id INTEGER NOT NULL CONSTRAINT c_field_load_on_field_default_pk PRIMARY KEY, field_id INTEGER, f_use_table_detail TEXT, f_set_to_detail TEXT, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_master_form_label ( id INTEGER NOT NULL CONSTRAINT c_master_form_label_pk PRIMARY KEY, company_id INTEGER NOT NULL, bu_id INTEGER NOT NULL, number_format TEXT, preview_number TEXT, sequence_name TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, warehouse_id INTEGER, tipe_label TEXT, sequence_batch_name TEXT )",
            "CREATE TABLE c_master_form_label_detail ( id INTEGER NOT NULL CONSTRAINT c_master_form_label_detail_pk PRIMARY KEY, master_form_label_id INTEGER, param_name TEXT, data_type TEXT, source_value TEXT, index_field INTEGER, sparator TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, source_field_value INTEGER )",
            "CREATE TABLE c_print_layout_generate_label ( id INTEGER NOT NULL CONSTRAINT c_print_layout_generate_label_pk PRIMARY KEY, caption TEXT NOT NULL, company_id INTEGER, bu_id INTEGER NOT NULL, custom_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, print_type TEXT )",
            "CREATE TABLE c_print_layout_generate_label_detail_page ( id INTEGER NOT NULL CONSTRAINT c_print_layout_generate_label_detail_page_pk PRIMARY KEY, print_layout_generate_label_id INTEGER, content_name TEXT NOT NULL, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_print_layout_generate_label_detail_content ( id INTEGER NOT NULL CONSTRAINT c_print_layout_generate_label_detail_content_pk PRIMARY KEY, border_id text, border_style text, content_id text, content_style text, content_text text, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, print_layout_generate_label_page_id INTEGER, box_style text, print_layout_group_id INTEGER )",
            "CREATE TABLE c_print_layout_generate_label_detail_group ( id INTEGER NOT NULL CONSTRAINT c_print_layout_generate_label_detail_group_pk PRIMARY KEY, print_layout_generate_label_page_id INTEGER NOT NULL, group_id text, style_group text, style_border text, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_custom_report_chart ( id INTEGER NOT NULL CONSTRAINT c_custom_report_chart_pk PRIMARY KEY, custom_report_id INTEGER NOT NULL, subject_chart TEXT, value_chart TEXT, color_chart TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, f_delete TEXT, caption_chart TEXT )",
            "CREATE TABLE c_custom_report_link_to ( id INTEGER NOT NULL CONSTRAINT c_custom_report_link_to_pk PRIMARY KEY, custom_header_id INTEGER NOT NULL, custom_report_id INTEGER, field_name TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_custom_report_link_to_parameter ( id INTEGER NOT NULL CONSTRAINT c_custom_report_link_to_parameter_pk PRIMARY KEY, parameter_field_dst TEXT, parameter_field_src TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, custom_link_to_id INTEGER NOT NULL )",
            "CREATE TABLE c_create_using_scan_qr ( id INTEGER NOT NULL CONSTRAINT c_create_using_scan_qr_pk PRIMARY KEY, custom_id INTEGER NOT NULL, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, f_delete TEXT, version INTEGER )",
            "CREATE TABLE c_create_from_reference ( id INTEGER NOT NULL CONSTRAINT c_create_from_reference_pk PRIMARY KEY, custom_id INTEGER NOT NULL, src_key TEXT, dst_key TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE c_group_access_sales_menu_default ( id INTEGER NOT NULL CONSTRAINT c_group_access_sales_menu_default_id_pk PRIMARY KEY, group_id INTEGER NOT NULL, f_attendance TEXT, f_journey TEXT, f_stock TEXT, f_news TEXT, f_stock_report TEXT, f_visit_report TEXT, f_akun TEXT, f_sales_report TEXT, f_stock_count_report TEXT, f_visit_note_report TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, f_dealer_orders TEXT, f_retail_sales TEXT, f_stock_count_outlet TEXT, f_visit_note TEXT )",
            "CREATE TABLE c_custom_report_field_color ( id INTEGER NOT NULL CONSTRAINT c_custom_report_field_color_pk PRIMARY KEY, custom_report_field_id INTEGER NOT NULL, indikator TEXT, color_field TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER )",
            "CREATE TABLE f_dynamic_table ( id INTEGER NOT NULL PRIMARY KEY, company_id INTEGER, table_name TEXT, table_caption TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, version INTEGER, f_table_view TEXT, sequence_name TEXT, salesunit_id INTEGER, customer_id INTEGER, f_from_view TEXT, view_name TEXT, f_table_schedule TEXT, module_origin_id INTEGER, f_ckeditor TEXT, history_table TEXT, is_project TEXT, f_table_generate_label TEXT, table_generate_id INTEGER, is_project_detail TEXT, f_table_reference TEXT )",
            'CREATE TABLE f_dynamic_table_detail ( id INTEGER NOT NULL PRIMARY KEY, table_id INTEGER, column_name TEXT, column_caption TEXT, data_type TEXT, length INTEGER, precision INTEGER, f_pk TEXT, f_uk TEXT, f_default TEXT, dropdown_value TEXT, f_dropdown_list TEXT, dropdown_list_id INTEGER, f_textarea TEXT, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, src_table_id INTEGER, src_column_id INTEGER, max_length_numeric INTEGER, upload_live TEXT, minimum_length INTEGER, f_unique TEXT, f_ckeditor TEXT, f_desc_value TEXT, "index" REAL )',
            "CREATE TABLE f_dynamic_table_trigger ( id INTEGER NOT NULL PRIMARY KEY, table_id INTEGER, trigger_name TEXT, trigger_state TEXT, trigger_operation TEXT )",
            "CREATE TABLE f_dynamic_table_trigger_action ( id INTEGER NOT NULL PRIMARY KEY, trigger_id INTEGER, sequence_index INTEGER, action_name TEXT, action_function TEXT, dest_table_name TEXT )",
            "CREATE TABLE f_dynamic_table_trigger_variable ( id INTEGER NOT NULL PRIMARY KEY, trigger_id INTEGER, variable_name TEXT, source_table_name TEXT, column_key TEXT, operation TEXT, column_value TEXT )",
            "CREATE TABLE f_dynamic_table_trigger_action_detail ( id INTEGER NOT NULL PRIMARY KEY, action_id INTEGER, action_mode TEXT, f_manual_key TEXT, column_key TEXT, operation TEXT, f_manual_value TEXT, f_variable TEXT, variable_name TEXT, column_value TEXT, operand TEXT, index_field INTEGER, f_sequence_id TEXT )",
            "CREATE TABLE f_dynamic_table_header ( id INTEGER NOT NULL PRIMARY KEY, table_detail_id INTEGER, table_header_id INTEGER, create_date TEXT NOT NULL, create_who TEXT NOT NULL, change_date TEXT, change_who TEXT, company_id INTEGER, custom_id INTEGER )",
            'CREATE TABLE t_dynamic_chart ( id INTEGER PRIMARY KEY, title TEXT, type TEXT, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT, segment_id INTEGER, company_id INTEGER, show TEXT, "index" INTEGER, size TEXT, start_date_on_load TEXT, date_filter_field TEXT, config_1 TEXT, f_filter TEXT, config_2 TEXT, config_3 TEXT, f_delete TEXT, user_filter_field TEXT )',
            "CREATE TABLE t_dynamic_chart_detail ( id INTEGER PRIMARY KEY, id_chart INTEGER, name TEXT, axis TEXT, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT, field_name TEXT, config_1 TEXT )",
            "CREATE TABLE t_dynamic_report ( id INTEGER PRIMARY KEY, name TEXT, description TEXT, style TEXT, company_id INTEGER, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT, custom_id INTEGER, f_delete TEXT, doc_type TEXT, f_inactive TEXT, additional_id INTEGER )",
            "CREATE TABLE t_dynamic_report_detail ( id INTEGER PRIMARY KEY, report_id INTEGER, name TEXT, style TEXT, value_text TEXT, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT, company_id INTEGER, group_name TEXT, element_type TEXT, element_caption TEXT, f_page_layout TEXT, f_by_page_break TEXT, page_number TEXT )",
            "CREATE TABLE t_dynamic_schedule_mapping ( id INTEGER PRIMARY KEY, schedule_column TEXT, master_column TEXT, table_master_id INTEGER, table_schedule_id INTEGER, custom_form_id INTEGER, data_type TEXT, create_who TEXT NOT NULL, create_date TEXT NOT NULL, change_who TEXT, change_date TEXT )",
            "CREATE TABLE t_dynamic_report_access ( id INTEGER PRIMARY KEY, report_id INTEGER, user_id INTEGER, f_group TEXT, create_date TEXT, create_who TEXT, change_date TEXT, change_who TEXT )",
            "CREATE TABLE m_sales_channel ( sales_channel_id INTEGER NOT NULL PRIMARY KEY, sales_channel_code VARCHAR(20), sales_channel_desc VARCHAR(128), f_inactive VARCHAR(1), create_date TIMESTAMP NOT NULL, create_who VARCHAR(32) NOT NULL, change_date TIMESTAMP, change_who VARCHAR(32), company_id BIGINT, version BIGINT )",
            "CREATE TABLE m_sales_structure ( sales_structure_id INTEGER NOT NULL PRIMARY KEY, sales_position VARCHAR(16), sales_structure_code VARCHAR(20), sales_structure_desc VARCHAR(128), sales_channel_id BIGINT, sales_subchannel_id BIGINT, sales_subdivision_id BIGINT, f_inactive VARCHAR(1), create_date TIMESTAMP NOT NULL, create_who VARCHAR(32) NOT NULL, change_date TIMESTAMP, change_who VARCHAR(32), company_id BIGINT, version BIGINT, f_all_customer VARCHAR(1) )",
            "CREATE TABLE m_sales_structure_detail ( sales_structure_detail_id INTEGER NOT NULL PRIMARY KEY, sales_structure_upper_id BIGINT NOT NULL, sales_structure_lower_id BIGINT, create_date TIMESTAMP NOT NULL, create_who VARCHAR(32) NOT NULL, change_date TIMESTAMP, change_who VARCHAR(32), company_id BIGINT )",
            "CREATE TABLE m_sales_subchannel ( sales_subchannel_id INTEGER NOT NULL PRIMARY KEY, sales_channel_id BIGINT, sales_subchannel_code VARCHAR(20), sales_subchannel_desc VARCHAR(128), f_inactive VARCHAR(1), create_date TIMESTAMP NOT NULL, create_who VARCHAR(32) NOT NULL, change_date TIMESTAMP, change_who VARCHAR(32), salesunit_id BIGINT, company_id BIGINT, version BIGINT )",
            "CREATE TABLE m_sales_subdivision ( sales_subdivision_id INTEGER NOT NULL PRIMARY KEY, sales_subchannel_id BIGINT, sales_subdivision_code VARCHAR(20), sales_subdivision_desc VARCHAR(128), f_inactive VARCHAR(1), create_date TIMESTAMP NOT NULL, create_who VARCHAR(32) NOT NULL, change_date TIMESTAMP, change_who VARCHAR(32), salesunit_id BIGINT, company_id BIGINT, version BIGINT )",
            "CREATE TABLE m_salesunit ( salesunit_id INTEGER NOT NULL PRIMARY KEY, bu_id BIGINT, salesunit_name VARCHAR(128), create_date TIMESTAMP NOT NULL, create_who VARCHAR(32) NOT NULL, change_date TIMESTAMP, change_who VARCHAR(32), f_canvasser VARCHAR(1), warehouse_id BIGINT, customer_id BIGINT, f_inactive VARCHAR(1), salesgroup_id BIGINT, salestype_id BIGINT, level_id BIGINT, user_name VARCHAR(30), password VARCHAR(100), session_id VARCHAR(1000), login_date TIMESTAMP, login_time TIMESTAMP, f_active VARCHAR(1), sales_channel_id BIGINT, sales_subchannel_id BIGINT, sales_subdivision_id BIGINT, imei_phone VARCHAR(32), outlet_version NUMERIC, f_include_photo VARCHAR(1), sales_position VARCHAR(16), attendance_config VARCHAR(3), sales_structure_id BIGINT, f_stock_count VARCHAR(1), parent_warehouse_id BIGINT, f_use_fingerprint VARCHAR(1), nik VARCHAR(256), salesunit_code VARCHAR(128), f_using_sfa VARCHAR(1), f_show_stock_all_warehouse CHAR(1), last_latitude NUMERIC, last_longitude NUMERIC, f_active_tracking CHAR(1), last_update_location TIMESTAMP, version BIGINT, f_allow_edit_price_sfa VARCHAR(1), group_access_id BIGINT, f_visit_include_photo VARCHAR(1), company_id BIGINT, fcm_token VARCHAR(255), create_user_web_no_sfa VARCHAR(1), create_user_web_with_sfa VARCHAR(1), join_date TIMESTAMP, resign_date TIMESTAMP, gmails VARCHAR(255), f_show_qrcode VARCHAR(2), attendance_method TEXT, f_can_scan_qrcode_team VARCHAR(2), f_strict_location_in VARCHAR(2), f_strict_location_out VARCHAR(2), visit_photo_mode_id BIGINT, validate_nik_and_npwp_new_customer VARCHAR(2) )",
          ];

          Batch batch = db.batch();

          for (var tableScript in tableScripts) {
            batch.execute(tableScript);
          }

          await batch.commit(noResult: true);
        },
      );

      if (kDebugMode) {
        print("Sqlites: successfully opened database");
      }
    }

    return database!;
  }

  static void delete() async {
    await deleteDatabase("${await getDatabasesPath()}/dynamic_of_things.db");

    if (database != null) {
      await database!.close();

      database = null;
    }

    await BasePreferences.getInstance().remove("dot-sales-unit-id");
    await BasePreferences.getInstance().remove("dot-username");
    await BasePreferences.getInstance().remove("dot-business-unit-id");
    await BasePreferences.getInstance().remove("dot-business-unit-code");
    await BasePreferences.getInstance().remove("dot-user-id");
    await BasePreferences.getInstance().remove("dot-company-id");
    await BasePreferences.getInstance().remove("dot-sync-current-version");
  }

  static String dataType(String value) {
    if (StringUtils.equalsIgnoreCase(value, "DATETIME")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "DATE")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "IMEI")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "DATA")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "FILE")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "CHECKBOX")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "COMBOBOX")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "MULTIDATA")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "STRING")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "NUMERIC")) {
      return "NUMERIC";
    } else if (StringUtils.equalsIgnoreCase(value, "EMAIL")) {
      return "TEXT";
    } else if (StringUtils.equalsIgnoreCase(value, "PASSWORD")) {
      return "TEXT";
    } else {
      return "TEXT";
    }
  }
}
